name: Chartstoppers
author: Adrian Sampson
url: http://chartstoppers.radbox.org/

markdown: kramdown
highlighter: null

exclude:
    - bower_components
    - node_modules

collections:
    eps:
        output: true
        permalink: /:path/
defaults:
    -
        scope:
            path: ""
            type: eps
        values:
            layout: ep
