name: Chartstoppers
url: http://chartstoppers.com/
feed: feed.xml

markdown: kramdown
highlighter: null

exclude:
    - bower_components
    - node_modules
    - Makefile
    - logs
    - report.html

collections:
    eps:
        output: true
        permalink: /:path/
    drafteps:
        output: true
        permalink: /draft/:path/
defaults:
    -
        scope:
            path: ""
            type: eps
        values:
            layout: ep
    -
        scope:
            path: ""
            type: drafteps
        values:
            layout: ep
