name: Chartstoppers
url: http://chartstoppers.radbox.org/

markdown: kramdown
highlighter: null

exclude:
    - bower_components
    - node_modules

collections:
    eps:
        output: true
        permalink: /:path/
defaults:
    -
        scope:
            path: ""
            type: eps
        values:
            layout: ep

podcast:
    description: Hello.
    copyright: something
    subtitle: The charts never sounded this good.
    author: Eric Peterson and Adrian Sampson
    explicit: yes
    email: adrian@radbox.org
    category: Music
    image: art.jpg
    keywords: pop, music, charts, billboard, reviews
    description: |
        Summary of the podcast goes here.
